services:
  - type: web
    name: n8n
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8nDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8nDB
          property: password
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 10

     - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
     - N8N_PORT=5678
     - N8N_PROTOCOL=https
     - NODE_ENV=production
     - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
     
databases:
  - name: n8nDB
    plan: starter
